### PR TITLE
Basic ROM evaluation script

### PR DESCRIPTION
**Pull request by sdrave**
Requires current pyMOR main due to minor change in `ListVectorArray` implementation.

For 8 global refinements I get a speedup factor of around 17 on my machine.

### CODE REVIEW

**Comment by renefritze** [comment]
CI now uses the necessary post-release version of pyMOR. 

This means the deal.II image still needs the patched version of preCICE, right @DavidSCN?
Do you produce debian packages for the preCICE development branch too? That would be simplest to jsut replace the 2.3.0 deb.

In the pyMOR docker image runs we're running into non-convergence (again/still?) it seems.

**Comment by DavidSCN** [comment]
> This means the deal.II image still needs the patched version of preCICE, right @DavidSCN?

Yes, we need the updated version of preCICE and no, we don't publish a dev version of preCICE packages. I guess building from source is still trivial and I can take care of it.

> In the pyMOR docker image runs we're running into non-convergence (again/still?) it seems.

Will have a look as well

**Comment by DavidSCN** [comment]
The new preCICE version will be released in April. I would propose to wait with the CI update until then and live with the failing CI for now.

**Comment by renefritze** [comment]
> The new preCICE version will be released in April. I would propose to wait with the CI update until then and live with the failing CI for now.

The problem with the pyMOR image-based runs is still there and unrelated though, right?

**Comment by DavidSCN** [comment]
@sdrave Did you measure this speedup for deal.II compiled in release mode or in debug mode? In release mode, I measure a speedup of 10 for 8 refinement levels.

**Pull request merged**
