### PR TITLE
Move assemble rhs

### PR DESCRIPTION
**Pull request by sdrave**
- The first commit takes care of moving the rhs assembly code into the `coupling_input_operator`. Along the way, I have also moved the setting of the initial condition from `initialize_precice` to a dedicated method.

- In the second commit I have altered the communication order in a way which is simpler and makes more sense to me. Of course, this is no longer mathematically equivalent to the original code, so please check if the change is reasonable.

- I am wondering whether we should remove the setting of an inital approximation to further simplify things.

### CODE REVIEW

**Comment by DavidSCN** [comment]
@sdrave is there a certain version of pyMOR required or do you have uncommitted changes? I receive the following error when using your branch and applying the ROM
```bash
.local/lib/python3.8/site-packages/pymor/algorithms/projection.py", line 112, in <lambda>
    @match_generic(lambda op: op.linear and not op.parametric, 'linear and not parametric')
AttributeError: 'CouplingInputOperator' object has no attribute 'linear'
```

>  The first commit takes care of moving the rhs assembly code into the coupling_input_operator. Along the way, I have also moved the setting of the initial condition from initialize_precice to a dedicated method.

Sounds good.

>    In the second commit I have altered the communication order in a way which is simpler and makes more sense to me. Of course, this is no longer mathematically equivalent to the original code, so please check if the change is reasonable.

Looks reasonable and actually more preCICE native. I don't remmeber the exact reason why I put it once this way.

> I am wondering whether we should remove the setting of an inital approximation to further simplify things.

We could do that considering that the initial field function is just a constant at the moment. Then we would have just 'zero' as initial guess. Even in the deal.II code the initial guess are only three lines of code which can be added again in case they become important.

**Comment by sdrave** [comment]
@DavidSCN, sorry, actually forgot to check the reduced case. Code should work now.

**Review by DavidSCN — APPROVED** [review]
Looks good and the results are correct as well. For documentation purposes: The reduced order model still results in a warning 
```bash
|WARNING|CouplingInputOperator: Using inefficient generic projection operator
```
I guess this stems from pyMOR. 

Another remark: I thought now that the RHS assembly (the integration in the coupling input operator) is reduced as well, we don't need to call it when using the reduced model. However, it seems that it is still applied when using the ROM. Other than that this can be merged, I will do some final clean-up before our next meeting.

**Comment by sdrave** [comment]
@DavidSCN, right, so far `coupling_input_operator` could not actually be reduced since for the reduction the adjoint operator is needed (the reduced basis is in the range of the operator, not its source). I have now verified that the operator really is self-adjoint and implemented `apply_adjoint` accordingly. Now the reduction works. (Of course, one still has to form inner products of the high-dimensional data coming from preCICE in the online phase.)

**Comment by DavidSCN** [comment]
Perfect, I guess this is now ready to go. I will add some final clean-up until next week.

**Pull request merged**
